project_id = "idzeiqycitwaaklhgmql"

[functions.doorai-chat]
verify_jwt = false

[functions.homepage-coach]
verify_jwt = false

[functions.seed-admin-users]
verify_jwt = false

[functions.get-profiles-with-email]
verify_jwt = false

[functions.scrape-events]
verify_jwt = false